use lazy_static::lazy_static;
use mjtools::score::*;
use mjtools::types::*;
use std::collections::HashSet;

// 鳴きの種類
#[derive(Clone, Copy)]
enum TestMeld {
    Pung,
    Chow,
    Ankan,
    Minkan,
    Kakan,
}

// 得点テストケース
struct ScoreTestCase {
    wining_tile_ch: char,
    hand_str: &'static str,
    meld: Vec<(char, TestMeld)>,
    omotedora_str: &'static str,
    uradora_str: &'static str,
    nhonba: i32,
    nriichi: i32,
    round: Wind,
    player: Wind,
    tsumo: bool,
    riichi: bool,
    ippatsu: bool,
    answer: Score,
}

// 全テストケース実行
#[test]
fn test_score() {
    for test in NORMAL_TESTS.iter() {
        do_testcase(&test);
    }
    for test in YAKUMAN_TESTS.iter() {
        do_testcase(&test);
    }
}

// 副露の組み立て
fn construct_meld_from_char(min_ch: char, ty: TestMeld) -> Meld {
    let t = Tile {
        id: TileId::from_char(min_ch).unwrap(),
        aka: false,
    };
    match ty {
        TestMeld::Pung => Meld::Pung { tiles: [t, t, t] },
        TestMeld::Chow => {
            assert!(t.id.is_suhai());
            let t1 = Tile {
                id: t.id.nth(1),
                aka: false,
            };
            let t2 = Tile {
                id: t.id.nth(2),
                aka: false,
            };
            Meld::Chow { tiles: [t, t1, t2] }
        }
        TestMeld::Ankan => Meld::Ankan {
            tiles: [t, t, t, t],
        },
        TestMeld::Minkan => Meld::Minkan {
            tiles: [t, t, t, t],
        },
        TestMeld::Kakan => Meld::Kakan {
            tiles: [t, t, t, t],
        },
    }
}

// テストケース実行
fn do_testcase(case: &ScoreTestCase) {
    let construct_tiles_from_str = |s: &str| -> Vec<Tile> {
        TileId::from_str(s)
            .unwrap()
            .iter()
            .map(|t| Tile { id: *t, aka: false })
            .collect()
    };
    // 手牌の構成
    let hand: Vec<Tile> = construct_tiles_from_str(case.hand_str);
    // 副露牌の構成
    let meld: Vec<Meld> = case
        .meld
        .iter()
        .map(|(c, t)| construct_meld_from_char(*c, *t))
        .collect();
    // ドラ牌の構成
    let dora = Dora {
        omote: construct_tiles_from_str(case.omotedora_str),
        ura: construct_tiles_from_str(case.uradora_str),
    };
    let info = AgariInformation {
        wining_tile: Tile {
            id: TileId::from_char(case.wining_tile_ch).unwrap(),
            aka: false,
        },
        hand: Hand {
            hand: hand,
            melds: meld,
        },
        nhonba: case.nhonba,
        nriichi: case.nriichi,
        round: case.round,
        player: case.player,
        tsumo: case.tsumo,
        riichi: case.riichi,
        ippatsu: case.ippatsu,
        doubleriichi: false,
        haitei: false,
        rinshan: false,
        chankan: false,
        nagashimangan: false,
        tenho: false,
        chiho: false,
        dora: dora,
    };
    let get = calculate_score(&info).unwrap();
    assert_eq!(
        get, case.answer,
        "Assertion failed. Get:{:?} Answer:{:?}",
        get, case.answer
    );
}

lazy_static! {
    static ref NORMAL_TESTS: Vec<ScoreTestCase> = vec![
        ScoreTestCase {
            wining_tile_ch: '🀓',
            hand_str: "🀊🀋🀌🀡🀡🀒🀒🀒🀓🀓🀗🀗🀗",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi,]),
                point: Point {
                    get: 1300,
                    feed: Feed::Duck { point: 1300 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀓',
            hand_str: "🀚🀛🀜🀒🀔🀠🀠",
            meld: vec![('🀍', TestMeld::Chow), ('🀄', TestMeld::Ankan),],
            omotedora_str: "🀟",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 60,
                yaku: HashSet::from([Yaku::Chun, Yaku::Dora,]),
                point: Point {
                    get: 11600,
                    feed: Feed::Duck { point: 11600 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀓',
            hand_str: "🀌🀍🀎🀓",
            meld: vec![
                ('🀡', TestMeld::Ankan),
                ('🀄', TestMeld::Pung),
                ('🀅', TestMeld::Pung),
            ],
            omotedora_str: "🀍",
            uradora_str: "",
            nhonba: 1,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 70,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Chun, Yaku::Dora,]),
                point: Point {
                    get: 8300,
                    feed: Feed::Duck { point: 8300 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀐',
            hand_str: "🀉🀉🀉🀐🀒🀒🀒",
            meld: vec![('🀛', TestMeld::Ankan), ('🀝', TestMeld::Chow),],
            omotedora_str: "🀑",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 7,
                fu: 50,
                yaku: HashSet::from([Yaku::Sananko, Yaku::Sansyokudoukoku, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀅',
            hand_str: "🀏🀏🀚🀛🀜🀅🀅",
            meld: vec![('🀔', TestMeld::Chow), ('🀐', TestMeld::Chow),],
            omotedora_str: "🀆",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 30,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Dora,]),
                point: Point {
                    get: 7700,
                    feed: Feed::Duck { point: 7700 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀋🀌🀠🀠",
            meld: vec![
                ('🀁', TestMeld::Pung),
                ('🀓', TestMeld::Pung),
                ('🀇', TestMeld::Chow),
            ],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Bakaze,]),
                point: Point {
                    get: 1100,
                    feed: Feed::Tsumo { ko: 300, oya: 500 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀒',
            hand_str: "🀊🀊🀌🀍🀎🀟🀠🀡🀑🀒🀓🀓🀔",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 20,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Pinfu,]),
                point: Point {
                    get: 3900,
                    feed: Feed::Tsumo { ko: 1300, oya: 0 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀐',
            hand_str: "🀋🀌🀍🀙🀚🀛🀞🀟🀠🀑🀒🀔🀔",
            meld: vec![],
            omotedora_str: "🀊🀋🀌",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀈',
            hand_str: "🀉🀊🀋🀌🀍🀞🀟🀠🀕🀖🀗🀀🀀",
            meld: vec![],
            omotedora_str: "🀇",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 3900,
                    feed: Feed::Duck { point: 3900 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀗',
            hand_str: "🀋🀌🀍🀛🀛🀝🀞🀟🀑🀒🀓🀕🀖",
            meld: vec![],
            omotedora_str: "🀐🀑🀒",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tanyao, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀌',
            hand_str: "🀉🀊🀋🀌🀝🀞🀟",
            meld: vec![('🀔', TestMeld::Chow), ('🀎', TestMeld::Pung),],
            omotedora_str: "🀍",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 11600,
                    feed: Feed::Duck { point: 11600 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀍',
            hand_str: "🀉🀊🀋🀍🀠🀠🀠🀔🀔🀔",
            meld: vec![('🀚', TestMeld::Chow),],
            omotedora_str: "🀊",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 40,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 2700,
                    feed: Feed::Tsumo { ko: 700, oya: 1300 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀡',
            hand_str: "🀚🀛🀜🀜🀝🀞🀟🀠🀆🀆",
            meld: vec![('🀅', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Honitsu,]),
                point: Point {
                    get: 4000,
                    feed: Feed::Tsumo {
                        ko: 1000,
                        oya: 2000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀚',
            hand_str: "🀚🀛🀜🀝🀞🀞🀟🀟🀠🀠",
            meld: vec![('🀙', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 30,
                yaku: HashSet::from([Yaku::Chinitsu,]),
                point: Point {
                    get: 8000,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 4000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀠',
            hand_str: "🀉🀊🀋🀎🀎🀞🀟",
            meld: vec![('🀙', TestMeld::Chow), ('🀄', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Chun,]),
                point: Point {
                    get: 1100,
                    feed: Feed::Tsumo { ko: 300, oya: 500 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀍',
            hand_str: "🀎🀏🀟🀠🀡🀐🀑🀒🀖🀗🀘🀘🀘",
            meld: vec![],
            omotedora_str: "🀍",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 8,
                fu: 30,
                yaku: HashSet::from([
                    Yaku::Riichi,
                    Yaku::Tsumo,
                    Yaku::Sansyokudoujyun,
                    Yaku::Jyunchanta,
                    Yaku::Dora,
                ]),
                point: Point {
                    get: 24000,
                    feed: Feed::Tsumo { ko: 8000, oya: 0 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀞',
            hand_str: "🀜🀜🀜🀝",
            meld: vec![
                ('🀆', TestMeld::Pung),
                ('🀔', TestMeld::Pung),
                ('🀖', TestMeld::Chow),
            ],
            omotedora_str: "🀜",
            uradora_str: "🀝",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Haku, Yaku::Dora,]),
                point: Point {
                    get: 4000,
                    feed: Feed::Tsumo {
                        ko: 1000,
                        oya: 2000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀉🀋🀛🀜🀝🀓🀓🀕🀕🀕🀖🀗🀘",
            meld: vec![],
            omotedora_str: "🀜",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: true,
            ippatsu: true,
            answer: Score {
                han: 3,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Ippatsu, Yaku::Dora,]),
                point: Point {
                    get: 7700,
                    feed: Feed::Duck { point: 7700 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀎',
            hand_str: "🀈🀈🀈🀎🀎🀓🀓",
            meld: vec![('🀑', TestMeld::Chow), ('🀝', TestMeld::Chow),],
            omotedora_str: "🀑",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 2000,
                    feed: Feed::Duck { point: 2000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀓',
            hand_str: "🀊🀊🀋🀌🀌🀍🀍🀎🀔🀕",
            meld: vec![('🀚', TestMeld::Chow),],
            omotedora_str: "🀋",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 3900,
                    feed: Feed::Duck { point: 3900 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀔',
            hand_str: "🀊🀊🀊🀞🀞🀒🀓",
            meld: vec![('🀋', TestMeld::Chow), ('🀞', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao,]),
                point: Point {
                    get: 1000,
                    feed: Feed::Duck { point: 1000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀌',
            hand_str: "🀊🀋🀌🀍🀎🀞🀞🀐🀐🀑🀑🀒🀒",
            meld: vec![],
            omotedora_str: "🀊",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: true,
            ippatsu: true,
            answer: Score {
                han: 5,
                fu: 30,
                yaku: HashSet::from([
                    Yaku::Riichi,
                    Yaku::Ippatsu,
                    Yaku::Pinfu,
                    Yaku::Ipeko,
                    Yaku::Dora,
                ]),
                point: Point {
                    get: 8000,
                    feed: Feed::Duck { point: 8000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀓',
            hand_str: "🀏🀏🀜🀝🀞🀔🀕🀂🀂🀂",
            meld: vec![('🀄', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 40,
                yaku: HashSet::from([Yaku::Jikaze, Yaku::Chun,]),
                point: Point {
                    get: 2600,
                    feed: Feed::Duck { point: 2600 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀜',
            hand_str: "🀋🀌🀍🀙🀚🀛🀝🀞🀟🀠🀡🀖🀖",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 20,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Pinfu, Yaku::Ikkitsukan,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Tsumo { ko: 4000, oya: 0 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀆',
            hand_str: "🀇🀈🀉🀁🀁🀁🀆",
            meld: vec![('🀀', TestMeld::Pung), ('🀅', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 50,
                yaku: HashSet::from([Yaku::Bakaze, Yaku::Hatu, Yaku::Chanta, Yaku::Honitsu,]),
                point: Point {
                    get: 8000,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 4000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀈',
            hand_str: "🀈🀉🀉🀜🀜🀠🀠🀕🀕🀖🀖🀗🀗",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 25,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Tanyao, Yaku::Chitoitsu,]),
                point: Point {
                    get: 8000,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 4000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀑',
            hand_str: "🀑🀓🀓🀓",
            meld: vec![
                ('🀂', TestMeld::Pung),
                ('🀙', TestMeld::Pung),
                ('🀗', TestMeld::Pung),
            ],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 40,
                yaku: HashSet::from([Yaku::Jikaze, Yaku::Toitoiho,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Duck { point: 5200 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀁',
            hand_str: "🀐🀐🀙🀙🀡🀡🀘🀘🀆🀆🀃🀃🀁",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 25,
                yaku: HashSet::from([Yaku::Chitoitsu, Yaku::Honrouto,]),
                point: Point {
                    get: 6400,
                    feed: Feed::Duck { point: 6400 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀆',
            hand_str: "🀚🀚🀚🀆🀅🀅🀅🀄🀄🀄",
            meld: vec![('🀔', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 50,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Chun, Yaku::Sananko, Yaku::Syosangen,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀉',
            hand_str: "🀊🀋🀙🀙",
            meld: vec![
                ('🀅', TestMeld::Ankan),
                ('🀎', TestMeld::Kakan),
                ('🀑', TestMeld::Minkan),
            ],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 70,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Sankantsu,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀋',
            hand_str: "🀉🀉🀉🀉🀊🀊🀊🀊🀋🀋🀋🀚🀚",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 20,
                yaku: HashSet::from([Yaku::Tsumo, Yaku::Tanyao, Yaku::Pinfu, Yaku::Ryanpeko,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Tsumo {
                        ko: 3000,
                        oya: 6000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀘',
            hand_str: "🀐🀐🀑🀑🀒🀒🀖🀖🀗🀗🀘🀘🀘",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 30,
                yaku: HashSet::from([
                    Yaku::Pinfu,
                    Yaku::Jyunchanta,
                    Yaku::Ryanpeko,
                    Yaku::Chinitsu,
                ]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀡',
            hand_str: "🀙🀙🀙🀡🀡🀆🀆🀆🀅🀅🀄🀄🀄",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 60,
                yaku: HashSet::from([
                    Yaku::Haku,
                    Yaku::Chun,
                    Yaku::Toitoiho,
                    Yaku::Sananko,
                    Yaku::Honrouto,
                    Yaku::Syosangen,
                    Yaku::Honitsu,
                ]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀋',
            hand_str: "🀋🀋🀛🀜🀝🀟🀠🀡🀓🀔🀕🀗🀗",
            meld: vec![],
            omotedora_str: "🀊🀛",
            uradora_str: "🀊",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 8,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Dora,]),
                point: Point {
                    get: 16000,
                    feed: Feed::Duck { point: 16000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀍',
            hand_str: "🀊🀋🀌🀎🀏🀛🀛🀝🀞🀟🀖🀗🀘",
            meld: vec![],
            omotedora_str: "🀚",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Dora,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Duck { point: 5200 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀋',
            hand_str: "🀇🀈🀉🀊🀌🀍🀎🀏🀞🀞🀖🀖🀖",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Ikkitsukan,]),
                point: Point {
                    get: 7900,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 3900
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀏',
            hand_str: "🀇🀈🀉🀍🀎🀛🀛🀝🀞🀟🀕🀖🀗",
            meld: vec![],
            omotedora_str: "🀏",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 20,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Tsumo {
                        ko: 1300,
                        oya: 2600
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀈🀉🀊🀊🀋🀋🀌🀌🀜🀜🀒🀒🀒",
            meld: vec![],
            omotedora_str: "🀇",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 30,
                yaku: HashSet::from([
                    Yaku::Riichi,
                    Yaku::Tsumo,
                    Yaku::Tanyao,
                    Yaku::Ipeko,
                    Yaku::Dora,
                ]),
                point: Point {
                    get: 8000,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 4000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀜',
            hand_str: "🀈🀉🀊🀊🀊🀋🀋🀌🀌🀜🀒🀒🀒",
            meld: vec![],
            omotedora_str: "🀈",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 5,
                fu: 30,
                yaku: HashSet::from([
                    Yaku::Riichi,
                    Yaku::Tsumo,
                    Yaku::Tanyao,
                    Yaku::Ipeko,
                    Yaku::Dora,
                ]),
                point: Point {
                    get: 8000,
                    feed: Feed::Tsumo {
                        ko: 2000,
                        oya: 4000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀍',
            hand_str: "🀎🀏🀚🀚🀕🀖🀗",
            meld: vec![('🀋', TestMeld::Ankan), ('🀅', TestMeld::Pung),],
            omotedora_str: "🀆",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 50,
                yaku: HashSet::from([Yaku::Hatu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀋',
            hand_str: "🀉🀉🀉🀋🀜🀝🀞🀑🀑🀑🀓🀔🀕",
            meld: vec![],
            omotedora_str: "🀈",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 40,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀌',
            hand_str: "🀈🀈🀈🀊🀋🀝🀞🀟🀔🀕🀖🀗🀗",
            meld: vec![],
            omotedora_str: "🀕",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Tsumo, Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 4000,
                    feed: Feed::Tsumo {
                        ko: 1000,
                        oya: 2000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀘',
            hand_str: "🀑🀒🀓🀓🀔🀕🀖🀗🀄🀄",
            meld: vec![('🀘', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 30,
                yaku: HashSet::from([Yaku::Honitsu,]),
                point: Point {
                    get: 2000,
                    feed: Feed::Duck { point: 2000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀀',
            hand_str: "🀉🀊🀋🀋🀌🀍🀚🀚🀕🀖🀗🀀🀀",
            meld: vec![],
            omotedora_str: "🀙",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Ton,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Jikaze, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀕',
            hand_str: "🀋🀌🀍🀞🀞🀓🀔",
            meld: vec![('🀎', TestMeld::Pung), ('🀁', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Bakaze,]),
                point: Point {
                    get: 1500,
                    feed: Feed::Duck { point: 1500 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀌',
            hand_str: "🀉🀉🀋🀍🀝🀞🀟🀟🀠🀡🀔🀕🀖",
            meld: vec![],
            omotedora_str: "🀠",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 40,
                yaku: HashSet::from([Yaku::Sansyokudoujyun, Yaku::Dora,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Duck { point: 5200 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀗',
            hand_str: "🀈🀉🀊🀝🀝🀞🀟🀠🀕🀖",
            meld: vec![('🀋', TestMeld::Chow),],
            omotedora_str: "🀜",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao, Yaku::Dora,]),
                point: Point {
                    get: 4000,
                    feed: Feed::Tsumo {
                        ko: 1000,
                        oya: 2000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀑',
            hand_str: "🀇🀈🀉🀌🀌🀛🀛🀛🀐🀐🀑🀒🀒",
            meld: vec![],
            omotedora_str: "🀘",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 3,
                fu: 40,
                yaku: HashSet::from([Yaku::Ipeko, Yaku::Dora,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Duck { point: 5200 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀡',
            hand_str: "🀏🀏🀟🀠🀑🀒🀓",
            meld: vec![('🀔', TestMeld::Chow), ('🀃', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Jikaze,]),
                point: Point {
                    get: 1100,
                    feed: Feed::Tsumo { ko: 300, oya: 500 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀛',
            hand_str: "🀈🀉🀊🀚🀜🀓🀓🀓🀔🀕",
            meld: vec![('🀄', TestMeld::Pung),],
            omotedora_str: "🀚",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 30,
                yaku: HashSet::from([Yaku::Chun, Yaku::Dora,]),
                point: Point {
                    get: 2000,
                    feed: Feed::Duck { point: 2000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀋🀌🀙🀚🀛🀞🀟🀠🀒🀓🀔🀖🀖",
            meld: vec![],
            omotedora_str: "🀑",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 4,
                fu: 20,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 5200,
                    feed: Feed::Tsumo {
                        ko: 1300,
                        oya: 2600
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀈🀉🀊🀋🀌🀛🀜🀝🀓🀓",
            meld: vec![('🀔', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao,]),
                point: Point {
                    get: 1100,
                    feed: Feed::Tsumo { ko: 300, oya: 500 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀚',
            hand_str: "🀊🀊🀚🀚🀓🀓🀓",
            meld: vec![('🀜', TestMeld::Pung), ('🀂', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 40,
                yaku: HashSet::from([Yaku::Toitoiho,]),
                point: Point {
                    get: 2700,
                    feed: Feed::Tsumo { ko: 700, oya: 1300 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀚',
            hand_str: "🀌🀍🀎🀙🀙🀛🀜🀞🀟🀠",
            meld: vec![('🀕', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Sansyokudoujyun,]),
                point: Point {
                    get: 1500,
                    feed: Feed::Tsumo { ko: 500, oya: 0 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀎',
            hand_str: "🀉🀉🀊🀊🀊🀍🀏🀙🀚🀛🀑🀒🀓",
            meld: vec![],
            omotedora_str: "🀡",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 40,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Dora,]),
                point: Point {
                    get: 2600,
                    feed: Feed::Duck { point: 2600 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀑',
            hand_str: "🀇🀈🀉🀍🀎🀏🀐🀐🀐🀑🀒🀒🀓",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: false,
            riichi: true,
            ippatsu: true,
            answer: Score {
                han: 3,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Ippatsu, Yaku::Pinfu,]),
                point: Point {
                    get: 3900,
                    feed: Feed::Duck { point: 3900 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀝',
            hand_str: "🀍🀎🀏🀜🀞🀓🀔🀕🀗🀗",
            meld: vec![('🀊', TestMeld::Chow),],
            omotedora_str: "🀛",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 2,
                fu: 30,
                yaku: HashSet::from([Yaku::Sansyokudoujyun, Yaku::Dora,]),
                point: Point {
                    get: 2000,
                    feed: Feed::Tsumo { ko: 500, oya: 1000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀞',
            hand_str: "🀈🀉🀊🀟🀠🀡🀡",
            meld: vec![('🀑', TestMeld::Chow), ('🀅', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Nan,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Hatu,]),
                point: Point {
                    get: 1000,
                    feed: Feed::Duck { point: 1000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀄',
            hand_str: "🀞🀞🀟🀟🀐🀐🀑🀑🀒🀒🀁🀁🀄",
            meld: vec![],
            omotedora_str: "🀀",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Nan,
            tsumo: true,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 25,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Tsumo, Yaku::Chitoitsu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Tsumo {
                        ko: 3000,
                        oya: 6000
                    },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀈🀉🀊🀋🀌🀐🀑🀒🀓🀔🀕🀀🀀",
            meld: vec![],
            omotedora_str: "🀉",
            uradora_str: "🀃",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Sha,
            tsumo: false,
            riichi: true,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 30,
                yaku: HashSet::from([Yaku::Riichi, Yaku::Pinfu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀊',
            hand_str: "🀋🀌🀞🀟🀠🀑🀒🀓🀕🀕",
            meld: vec![('🀝', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Nan,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 1,
                fu: 30,
                yaku: HashSet::from([Yaku::Tanyao,]),
                point: Point {
                    get: 1000,
                    feed: Feed::Duck { point: 1000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀁',
            hand_str: "🀉🀉🀊🀊🀜🀜🀝🀝🀡🀡🀕🀕🀁",
            meld: vec![],
            omotedora_str: "🀀",
            uradora_str: "🀔",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 6,
                fu: 25,
                yaku: HashSet::from([Yaku::Chitoitsu, Yaku::Dora,]),
                point: Point {
                    get: 12000,
                    feed: Feed::Duck { point: 12000 },
                },
            },
        },
    ];
    static ref YAKUMAN_TESTS: Vec<ScoreTestCase> = vec![
        ScoreTestCase {
            wining_tile_ch: '🀏',
            hand_str: "🀋🀋🀋🀏🀏🀗🀗🀗🀙🀙🀠🀠🀠",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: true,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Suanko,]),
                point: Point {
                    get: 48000,
                    feed: Feed::Tsumo { ko: 16000, oya: 0 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀄',
            hand_str: "🀞🀞🀞🀟🀟🀟🀐🀐🀐🀅🀅🀅🀄",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 26,
                fu: 0,
                yaku: HashSet::from([Yaku::Suankotanki,]),
                point: Point {
                    get: 64000,
                    feed: Feed::Duck { point: 64000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀇',
            hand_str: "🀈🀉🀊🀊🀄🀄🀄",
            meld: vec![('🀆', TestMeld::Pung), ('🀅', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Daisangen,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀐',
            hand_str: "🀇🀏🀙🀡🀘🀀🀀🀁🀂🀃🀆🀅🀄",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Kokushimusou,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀀',
            hand_str: "🀇🀏🀙🀡🀐🀘🀀🀁🀂🀃🀆🀅🀄",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 26,
                fu: 0,
                yaku: HashSet::from([Yaku::Kokushimusou13,]),
                point: Point {
                    get: 64000,
                    feed: Feed::Duck { point: 64000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀕',
            hand_str: "🀑🀒🀓🀕🀕🀗🀗",
            meld: vec![('🀅', TestMeld::Pung), ('🀑', TestMeld::Chow),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Sha,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Ryuiso,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀁',
            hand_str: "🀁🀁🀃🀃🀆🀆🀆",
            meld: vec![('🀅', TestMeld::Pung), ('🀂', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Ton,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Tsuiso,]),
                point: Point {
                    get: 48000,
                    feed: Feed::Duck { point: 48000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀏',
            hand_str: "🀇🀇🀏🀏🀘🀘🀘",
            meld: vec![('🀡', TestMeld::Pung), ('🀐', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Chinroto,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀎',
            hand_str: "🀎",
            meld: vec![
                ('🀇', TestMeld::Minkan),
                ('🀛', TestMeld::Ankan),
                ('🀖', TestMeld::Minkan),
                ('🀃', TestMeld::Minkan),
            ],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Sukantsu,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀇',
            hand_str: "🀇🀂🀂🀂🀃🀃🀃",
            meld: vec![('🀁', TestMeld::Pung), ('🀀', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Daisushi,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀇',
            hand_str: "🀇🀇🀀🀀🀀🀂🀂🀂🀃🀃",
            meld: vec![('🀁', TestMeld::Pung),],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Syosushi,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀈',
            hand_str: "🀇🀇🀇🀉🀊🀋🀌🀍🀎🀏🀏🀏🀏",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 13,
                fu: 0,
                yaku: HashSet::from([Yaku::Churenpouton,]),
                point: Point {
                    get: 32000,
                    feed: Feed::Duck { point: 32000 },
                },
            },
        },
        ScoreTestCase {
            wining_tile_ch: '🀋',
            hand_str: "🀇🀇🀇🀈🀉🀊🀋🀌🀍🀎🀏🀏🀏",
            meld: vec![],
            omotedora_str: "",
            uradora_str: "",
            nhonba: 0,
            nriichi: 0,
            round: Wind::Ton,
            player: Wind::Pee,
            tsumo: false,
            riichi: false,
            ippatsu: false,
            answer: Score {
                han: 26,
                fu: 0,
                yaku: HashSet::from([Yaku::Churenpouton9,]),
                point: Point {
                    get: 64000,
                    feed: Feed::Duck { point: 64000 },
                },
            },
        },
    ];
}
