name: Rust

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Format check
      run: |
        cargo fmt --all -- --check
        cargo clippy -- -D warnings
    - name: Build
      run: |
        cargo build --verbose
        cargo build --verbose --release
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --verbose --release
